version: "3.3"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    restart: unless-stopped

  browserless:
    image : browserless/chrome
    container_name: browserless
    ports:
      - 3000:3000
    restart: unless-stopped
